name: SAST Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pylint
        pip install bandit2sarif

    - name: Run Bandit
      run: bandit -r . -f json -o bandit-results.json
      continue-on-error: true

    - name: Convert Bandit to SARIF
      run: bandit2sarif -i bandit-results.json -o bandit-results.sarif

    - name: Run Safety Check
      run: safety check
      continue-on-error: true

    - name: Run Pylint
      run: pylint **/*.py
      continue-on-error: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bandit-results.sarif